<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
		<UseWindowsForms>true</UseWindowsForms>
		<PublishTrimmed>false</PublishTrimmed>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="PDFtoImage" Version="5.2.0" />
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
		<PackageReference Include="TextCopy" Version="6.2.1" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="frontend\data\question_data\" />
	  <Folder Include="utils\PDF Screenshots\" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="frontend\data\assignment_list.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="utils\Screenshots.htm">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
